# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build-test-lint
run-name: Build, test and lint by ${{ github.actor }}, PR ${{ github.ref }}

env:
  GH_WORKFLOW_TARGET: test-github-actions

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        check-latest: true
        cache: "pip"
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install development dependencies if they exist.
        if grep -q "dev = \[" pyproject.toml; then
            pip install -e '.[dev]'
        else
            pip install -e .
        fi
        pip install pylint pylint-exit
    - name: Run all tests
      run: |
        python -m unittest discover -s $GH_WORKFLOW_TARGET -p "*_test.py"
    - name: Run linter
      run: |
        pylint $GH_WORKFLOW_TARGET || pylint-exit --error-fail $?
