# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build, test and lint by ${{ github.actor }} on branch ${{ github.base_ref }}

env:
  GH_WORKFLOW_TARGET: test-github-actions

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install development dependencies if they exist.
        if grep -q "dev = [" pyproject.toml; then
            pip install -e .[dev]
        else
            pip install -e .
        fi
        # Install pylint with Google style guide.
        pip install pylint
        curl https://google.github.io/styleguide/pylintrc > pylintrc
    - name: Test with unittest
      run: |
        python -m unittest discover -s $GH_WORKFLOW_TARGET -p "*_test.py"
    - name: Lint with pylint
      run: |
        pylint --max-line-length=80 --indent-string='    ' $GH_WORKFLOW_TARGET
        # Parse pylint exit code
        exit_code=$?
        emit_code=0
        # Check for specific messages
        if [[ $((exit_code & 1)) -ne 0  ||   $((exit_code & 2)) -ne 0 ]]; then
            emit_code=$exit_code
        fi
        exit $emit_code
        
