# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build-test-lint
run-name: Build, test and lint by ${{ github.actor }}, PR ${{ github.ref }}

env:
  GH_WORKFLOW_TARGET: test-github-actions

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install development dependencies if they exist.
        if grep -q "dev = [" pyproject.toml; then
            pip install -e .[dev]
        else
            pip install -e .
        fi
        # Install pylint with Google style guide.
        pip install pylint
        curl https://google.github.io/styleguide/pylintrc > pylintrc
    - name: Test with unittest
      run: |
        python -m unittest discover -s $GH_WORKFLOW_TARGET -p "*_test.py"
    - name: Lint with pylint
      run: |
        lint_and_check_exit_code() {
          pylint --max-line-length=80 --indent-string='    ' $GH_WORKFLOW_TARGET
          local exit_code=$?
          # Parse pylint exit code
          binary_representation=$(echo "obase=2; $exit_code" | bc)
          # Check if the length of the binary representation is at least 2 characters
          if [ ${#binary_representation} -ge 2 ]; then
            first_two_bits=${binary_representation: -2:2}
            # Check for fatal or error messages
            if [ "$first_two_bits" != "00" ]; the
              return $exit_code
            fi
          fi
          return 0
        }
        lint_and_check_exit_code
        
